import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Sidebar from '@/app/components/Sidebar'
import { getServerSession } from 'next-auth';
import SessionProvider  from './components/SessionProvider';
import Header from '@/app/components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Spotify - Lecteur web',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession();
  return (
    <html lang="fr">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <main className='flex space-x-2 p-2 h-screen'>
            <Sidebar />
            <div className='flex flex-grow flex-col rounded-lg bg-[#121212]'> 
              <Header />
              {children}
            </div>
          </main>
        </SessionProvider>
        </body>
    </html>
  )
}
